# docker-compose.yml
version: '3.8'

services:
  # Self-hosted Portkey Gateway
  portkey-gateway:
    image: portkeyai/gateway:latest
    container_name: portkey-gateway
    ports:
      - "8787:8787"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database (Optional - only needed if SKIP_DATABASE=false)
  postgres:
    image: postgres:16-alpine
    container_name: shuscribe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shuscribe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - database  # Optional service - run with: docker-compose --profile database up

volumes:
  postgres_data: