[build]
builder = "NIXPACKS"
buildCommand = "uv sync --frozen"

[deploy]
startCommand = "uv run uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10