[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uv run hypercorn src.main:app --bind [::]:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10