"""
Database Schemas

This module aggregates all Pydantic models used for database interactions,
representing the core data structures of the application.
"""
from .story import (
    Chapter,
    ChapterCreate,
    ChapterUpdate,
    ChapterStatus,
    ChapterBase,
    FullStoryBase,
    StoryMetadata,
    StoryMetadataCreate,
    StoryMetadataUpdate,
)
from .user import (
    User,
    UserCreate,
    UserUpdate,
    UserBase,
    UserAPIKey,
    UserAPIKeyCreate,
    SubscriptionTier,
)
from .workspace import (
    Workspace,
    WorkspaceCreate,
    WorkspaceUpdate,
    WorkspaceBase,
    Arc,
)
from .agent import (
    AgentMessage,
    AgentConversation,
    AgentConversationCreate,
    AgentMetrics,
    AgentExecution,
    AgentExecutionCreate,
    AgentExecutionResult,
    UserFeedback,
    AgentType,
)
from .wiki import (
    WikiArticle,
    WikiArticleCreate,
    WikiArticleUpdate,
    WikiArticleType,
    ArticleConnection,
    ArticleConnectionCreate,
    ChapterVersion,
    ChapterVersionCreate,
    ChapterVersionUpdate,
    CurrentVersion,
    CurrentVersionCreate,
    CurrentVersionUpdate,
    WikiPage,
    WikiPageCreate,
    WikiPageUpdate,
    WikiPageBase,
    WikiArchive,
    WikiArchiveMetadata,
    WikiPageArticleLink,
    WikiPageArticleLinkBase,
    WikiPageArticleLinkCreate,
    WikiPageArticleLinkUpdate,
)


__all__ = [
    # Story
    "Chapter",
    "ChapterCreate",
    "ChapterUpdate",
    "ChapterStatus",
    "ChapterBase",
    "FullStoryBase",
    "StoryMetadata",
    "StoryMetadataCreate",
    "StoryMetadataUpdate",
    # User
    "User",
    "UserCreate",
    "UserUpdate",
    "UserBase",
    "UserAPIKey",
    "UserAPIKeyCreate",
    "SubscriptionTier",
    # Workspace
    "Workspace",
    "WorkspaceCreate",
    "WorkspaceUpdate",
    "WorkspaceBase",
    "Arc",
    # Agent
    "AgentMessage",
    "AgentConversation",
    "AgentConversationCreate",
    "AgentMetrics",
    "AgentExecution",
    "AgentExecutionCreate",
    "AgentExecutionResult",
    "UserFeedback",
    "AgentType",
    # Wiki
    "WikiArticle",
    "WikiArticleCreate",
    "WikiArticleUpdate",
    "WikiArticleType",
    "ArticleConnection",
    "ArticleConnectionCreate",
    "ChapterVersion",
    "ChapterVersionCreate",
    "ChapterVersionUpdate",
    "CurrentVersion",
    "CurrentVersionCreate",
    "CurrentVersionUpdate",
    "WikiPage",
    "WikiPageCreate",
    "WikiPageUpdate",
    "WikiPageBase",
    "WikiArchive",
    "WikiArchiveMetadata",
    "WikiPageArticleLink",
    "WikiPageArticleLinkBase",
    "WikiPageArticleLinkCreate",
    "WikiPageArticleLinkUpdate",
]
