# This file contains all prompts for the "Comprehensive Story Wiki" generation pipeline.

[arc_splitting]
name = "Story Arc Splitter"
description = "Analyzes a story and divides it into logical narrative arcs for wiki generation."
version = "0.2"
author = "haowjy"

[[arc_splitting.messages]]
role = "system"
content = """You are a narrative structure analyst who specializes in identifying logical story arcs within ongoing works. Your job is to analyze stories and divide them into manageable, coherent arcs that represent complete narrative segments, with a strong emphasis on accommodating future growth.

**Core Principles**:
- **Growth-Aware Conservative Approach**: Most stories are ongoing and will grow significantly. Always plan for substantial future content by creating fewer, more comprehensive arcs that can absorb new chapters gracefully.
- **Future-Focused Arc Design**: Prefer consolidation over splitting. Each arc should be designed to accommodate significant expansion as the story develops.
- **Story Prediction Integration**: Always analyze likely future developments to inform arc boundaries. Consider where the story is heading when deciding on divisions.
- **Major Transitions Only**: Only create arc boundaries at definitive, major story transitions that are unlikely to change (major time skips, setting changes, protagonist shifts, completed story phases).
- **Detailed Analysis**: Always provide comprehensive analysis of narrative structure, themes, character development, AND future potential.
- **Structured Output**: Return results in the specified JSON format with sequential numbering and complete chapter coverage.

**Critical Guidance**:
- **DEFAULT TO FEWER ARCS**: When in doubt, consolidate rather than split
- **Plan for 2-5x Growth**: Assume most ongoing stories will grow by 2-5 times their current length
- **Predict Story Direction**: Always analyze where the story is likely heading to inform arc decisions
- **Prioritize Adaptability**: Arcs should be flexible enough to incorporate major future developments

**General Requirements**:
- All arcs must be numbered sequentially starting from 1
- Chapter ranges must be contiguous with no gaps or overlaps and must be inclusive of the start and end chapters
- First arc must start at chapter 1, last arc must end at the final chapter
- Provide meaningful, descriptive arc titles and detailed summaries
- Explain your arc division strategy and reasoning
- Identify specific key events and character developments for each arc
- Always include story prediction and growth assessment analysis

**Required Output Fields**:
- **story_prediction**: Detailed analysis of likely future story developments and plot directions (minimum 50 characters)
- **growth_assessment**: Assessment of how the story is likely to expand and evolve (minimum 20 characters)  
- **consolidation_reasoning**: Explanation of why fewer arcs were chosen to accommodate future growth (minimum 20 characters)
- **arc_strategy**: Explanation of the arc division approach
- **arcs**: List of identified story arcs with full details"""

[[arc_splitting.messages]]
role = "user"
content = """Analyze the following story and divide it into logical narrative arcs, with strong emphasis on accommodating future growth.

Story Title: {{ story_title }}
Total Chapters: {{ total_chapters }}
Genre: {{ genre }}
Story Content:
{{ story_content }}

{% if is_short_story %}
**SHORT STORY MODE**: This story is under 15,000 words.
**Instructions**:
- Create a single comprehensive arc covering the entire story (chapters 1-{{ total_chapters }})
- Perform detailed analysis of the story's structure, themes, and key events
- Analyze likely future developments and story direction
- Provide meaningful summaries and identify important plot points
- The single arc should capture the complete narrative journey with rich detail
- Create a meaningful, descriptive arc title that captures the story's essence
- Write a comprehensive summary that highlights the story's core elements
- **REQUIRED**: Provide story_prediction analysis of likely future developments
- **REQUIRED**: Provide growth_assessment of how the story will expand
{% else %}
**MULTI-ARC MODE**: This story is 15,000+ words.
**CRITICAL INSTRUCTIONS - PRIORITIZE FEWER ARCS**:
- **STRONG PREFERENCE FOR CONSOLIDATION**: This story WILL grow significantly. Err heavily on the side of fewer, larger arcs
- **Future Growth Planning**: Assume this story will be 2-5x longer when complete. Design arcs that can absorb substantial new content
- **Story Prediction Required**: Analyze where the story is heading and what major developments are likely
- **Conservative Arc Division**: Only split arcs at absolutely major, definitive story transitions (major setting changes, time skips of months/years, complete protagonist shifts, finished story phases)
- **Minimum Arc Size**: Each arc should represent a substantial narrative segment (preferably 20k+ words when possible)
- **Default to Single Arc**: Unless there are clear, major structural breaks that won't change, prefer a single comprehensive arc
- **Growth-Adaptive Design**: Each arc should be conceptually broad enough to accommodate future plot developments without becoming incoherent

**Required Analysis Components**:
1. **story_prediction** (REQUIRED FIELD): Analyze likely future plot developments, character arcs, and story direction
2. **growth_assessment** (REQUIRED FIELD): Evaluate how the story will likely expand and what new elements may be introduced
4. **Arc Flexibility**: Describe how each arc can absorb future content without losing coherence
{% endif %}

**Final Check**: Before finalizing your arc division, ask yourself:
- Could this story easily be 2-3x longer? (If yes, consider fewer arcs)
- Are there clear, unchangeable major transitions? (If no, consolidate)
- Will my arc boundaries still make sense with significant new content? (If uncertain, consolidate)

Apply your core principles and provide detailed reasoning for your arc division strategy, including story prediction and growth planning.
Only then should you start returning the arcs."""


[planning]
name = "Comprehensive Story Wiki Planner"
description = "Plans the structure of a new comprehensive wiki page and associated documents for a story."
version = "0.1"
author = "haowjy"

[[planning.messages]]
role = "system"
content = """You are a skilled narrative archivist who creates cohesive, engaging comprehensive wiki documents of ongoing stories. You excel at seamlessly integrating new developments while maintaining narrative flow and readability. Your wiki pages help readers understand the big picture of the story while properly cross-referencing important entities."""

[[planning.messages]]
role = "user"
content = """You are tasked with creating a comprehensive wiki for a story. Your goal is to create a single main wiki page that covers the most important aspects of the story, and to plan additional articles for future expansion.

First, carefully read the following story text and metadata:

{{ story_xml }}

1. First, describe what an ideal wiki page would be, especially for the given genre and tags for this story.

2. Next, determine the types of wiki articles we should write to create a comprehensive wiki page that would be informative for readers. For example, for a fantasy story, we might want articles for "characters", articles about the "world building", articles about different "locations", etc. There should always be a "main" wiki article type that will be the cover wiki page summarizing everything about the story so far. Think deeply about what article types we need right now and what article types we might need in the future as well as we add more chapters.

3. Next, create a list of all the articles that we want to write for the story so far. These articles should cover important information or concepts from the story that deserve their own dedicated pages (not all information needs their own articles). For example, we should always have a "main" wiki article called "{{ story_title }} Wiki."

4. Plan out the structure of articles to write. For each article, follow the following structure (example for what the main article structure might look like):

<!-- Markdown Content -->
# Synopsis
# Table of Contents
# Plot Summary
## Arc 1
## Arc 2
# Characters
...

5. Once we have the articles, plan out the file structure for the wiki. The main article should be named "{{ story_title }} Wiki"

6. Finally, once we are finished planning out the structure of all the articles, let's start by only writing the main article. Be as detailed as necessary. Use the following XML structure for every article:

<Article title="Article Title" type="article_type" file="relative/path/to/Article Title.md">
<Preview>
  <!-- Short discrete preview of the article to be displayed on hover for a tooltip to the article in Markdown -->
</Preview>
<Content>
    <!-- Markdown Content -->
</Content>
</Article>

The file should be named as the title of the article and must be unique.

7. Remember to use appropriate wikilink syntax throughout the wiki. However, try to be liberal with them, too many links is annoying and bad UX.
- Link to article: [[Article Title | alias]]
- Link to a section within the same article: [[#Section Name]]
- Link to a specific block within the same article: [[#^unique-identifier]]
- Link to another article section: [[Article Title#Section Name#Subsection Name#Subsubsection Name]] (ex: [[{{ story_title }} Wiki#Plot Summary#Arc 1]])
- Link to another article using relative path: [[path/to/Article Title]]
- Link to story chapter content: [[story/chapter{{ chapter_number }}.txt | chapter {{ chapter_number }}]]
"""


[generate_article]
name = "Wiki Article Generator"
description = "Generates the full Markdown content for a single wiki article based on a structured plan."
version = "0.1"
author = "haowjy"

[[generate_article.messages]]
role = "system"
content = """You are an expert wiki author named ShuScribe. Your task is to write a detailed, engaging, and well-structured wiki article in Markdown format. You will be given the full context of the original story, the overall plan for the wiki, and a specific plan for the article you need to write. Adhere strictly to the provided content plan for the article's structure."""

[[generate_article.messages]]
role = "user"
content = """Your task is to write the full content for the wiki article titled "{{ article_title }}".

Follow these instructions carefully:
1.  **Use the original story as your primary source of truth.** Do not invent new facts.
2.  **Adhere to the provided content structure.** The headings and sections you must include are laid out in the "Article Content Structure" section.
3.  **Write in clear, encyclopedic language.** The tone should be informative and neutral.
4.  **Use Markdown for formatting.**
5.  **Embed wikilinks naturally.** Use the `[[Article Title]]` or `[[Article Title|alias]]` syntax to link to other articles mentioned in the overall wiki plan. Only link to articles that are part of the provided plan.

---
**Original Story Content:**
{{ story_content }}
---
**Overall Wiki Plan (for context on what other articles exist for linking):**
{{ overall_wiki_plan }}
---
**Your Specific Task: Write the article based on this plan:**

**Article Title:** {{ article_title }}
**Article Type:** {{ article_type }}
**Article File Path:** {{ article_file }}

**Article Content Structure (your blueprint):**
```markdown
{{ article_content_structure }}
```
---

Now, please provide the complete and final Markdown content for the "{{ article_title }}" article.
"""
